### ISSUE TITLE
500 internal error on 2.3.2 redmine- when deleting user account in admin page

### ISSUE THREAD

**Issue by fengyedou** [ande3577/redmine_daily_scrum#2]
Hi, I tested a bug which influences redmine default admin function. For an admin account, he may delete user account in some cases, like the member is not in the company now.

But when I delete user in admin - user, there will be a internal error, I checked the log, and tested much, found it is plug-in reason.

---

log is here：

Started DELETE "/redmine/users/3?back_url=%2Fredmine%2Fusers%3Fgroup_id%3D%26name%3Dtest%26status%3D%26utf8%3D%25E2%259C%2593" for 127.0.0.1 at 2014-12-23 17:09:24 +0800
Processing by UsersController#destroy as HTML
  Parameters: {"authenticity_token"=>"068x4GnF5VrvcU0T6q04sag/VVUaNr/r47epgXj+KtQ=", "back_url"=>"/redmine/users?group_id=&name=test&status=&utf8=%E2%9C%93", "id"=>"3"}
  Current user: xxx (id=1)
Completed 500 Internal Server Error in 365ms

ActiveRecord::StatementInvalid (Mysql2::Error: Unknown column 'post_scrum_actions.user_id' in 'where clause': SELECT `post_scrum_actions`.\* FROM `post_scrum_actions`  WHERE `post_scrum_actions`.`user_id` = 3):
  app/controllers/users_controller.rb:171:in `destroy'

**Comment by ande3577** [comment]
Should be fixed now.

**Comment by fengyedou** [comment]
@ande3577 
Hi, I download the latest plug-in and put it into redmine plug-in directory, after resart redmine I tested again, the same issue, not solved:(

You can check the error log:

Started DELETE "/redmine/users/30?back_url=%2Fredmine%2Fusers%3Fgroup_id%3D%26name%3Djinjin%26status%3D%26utf8%3D%25E2%259C%2593" for 127.0.0.1 at 2015-01-04 13:05:32 +0800
Processing by UsersController#destroy as HTML
  Parameters: {"authenticity_token"=>"ixZrxQFcR2dUi+2K3mm/ApDRh5Bl2EZ+BLCfeLuRHx8=", "back_url"=>"/redmine/users?group_id=&name=jinjin&status=&utf8=%E2%9C%93", "id"=>"30"}
  Current user: xxx (id=1)
Completed 500 Internal Server Error in 1407ms

ActiveRecord::StatementInvalid (Mysql2::Error: Table 'bitnami_redmine.daily_scrums' doesn't exist: SHOW FULL FIELDS FROM `daily_scrums`):
  app/controllers/users_controller.rb:171:in `destroy'

**Comment by ande3577** [comment]
I am now not able to recreate this his issue after the update.  Have you run the database migrations?

**Comment by fengyedou** [comment]
@ande3577 hi, sorry to reply late, I searched from the database and removed all daily scrum tables in the database, then migrate again, this time, the issue is fixed.

Thanks for your work!!By the way, do you have time to add the new feature, which I mentioned days before? To let daily scrum notes can be exported as a pdf file? Now we need to make daily scrum meeting minitues, we use wiki in redmine to record the daily meeting minutes, but if this plug-in can export contents, I think it will simply the meeting minutes effort.

Thanks again:)

**Comment by ande3577** [comment]
Sorry, have not had a chance to work on the export.  The pdf generation in redmine is a little clunky (it's mostly a manual process), so I haven't been too eager to try to tackle it.  Hopefully this weekend I can at least take a look at it and figure out how to make it work.
